name: Haithem Turki
avatar: images/profile.jpeg

google_analytics: G-3LEJEZQQQC
url: "https://haithemturki.com"

future: true
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - README.md
  - CHANGELOG.md
  - package.json
  - node_modules
  - vendor
  - assets/css/main.scss
  - _sass
  - style.scss
